In [31]:
import pandas as pd

## Creating the date table

### creating lables for the months

In [32]:
def make_label(row):
    if row["month"] == 1:
        return "Jan"
    elif row["month"] == 2:
        return "Feb"
    elif row["month"] == 3:
        return "Mar"
    elif row["month"] == 4:
        return "Apr"
    elif row["month"] == 5:
        return "Mai"
    elif row["month"] == 6:
        return "Jun"
    elif row["month"] == 7:
        return "Jul"
    elif row["month"] == 8:
        return "Aug"
    elif row["month"] == 9:
        return "Sep"
    elif row["month"] == 10:
        return "Oct"
    elif row["month"] == 11:
        return "Nov"
    elif row["month"] == 12:
        return "Dec"
    else:
        return "NULL"

In [33]:
 
def getDay(row):
    date = pd.to_datetime(row["Release"], format = "%Y/%m/%d")
# fetching the day
    return date.day_name()

In [34]:
everyNoise = pd.read_csv("CSVs/every-noise-at-once.csv")
everyNoise = everyNoise.dropna(subset=['Release'])
everyNoise = everyNoise.drop_duplicates(subset=['Release'])
everyNoise['month'] = (pd.DatetimeIndex(everyNoise['Release']).month)
everyNoise['year'] = (pd.DatetimeIndex(everyNoise['Release']).year)
everyNoise['day'] = (pd.DatetimeIndex(everyNoise['Release']).day)
everyNoise.day = everyNoise.day.astype(int)
everyNoise.month = everyNoise.month.astype(int)
everyNoise.year = everyNoise.year.astype(int)
date = everyNoise[["Release","day","month","year"]]
date['label'] = date.apply(lambda row: make_label(row),axis=1)
date['week_day'] = date.apply(lambda row: getDay(row),axis=1)

date  = date.drop_duplicates(subset=["Release"])

C:\Users\baraj\AppData\Local\Temp/ipykernel_1596/3941304145.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date['label'] = date.apply(lambda row: make_label(row),axis=1)
C:\Users\baraj\AppData\Local\Temp/ipykernel_1596/3941304145.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  date['week_day'] = date.apply(lambda row: getDay(row),axis=1)

In [35]:
date = date.drop_duplicates()
date.rename(columns={"label":"month_label"},inplace=True)

date

           Release  day  month  year month_label  week_day
0       2021-07-23   23      7  2021         Jul    Friday
1       2019-01-24   24      1  2019         Jan  Thursday
2       2016-03-11   11      3  2016         Mar    Friday
3       2021-06-04    4      6  2021         Jun    Friday
4       2018-12-14   14     12  2018         Dec    Friday
...            ...  ...    ...   ...         ...       ...
541751  1972-02-28   28      2  1972         Feb    Monday
542129  1986-08-26   26      8  1986         Aug   Tuesday
542916  1977-05-03    3      5  1977         Mai   Tuesday
542935  1993-09-06    6      9  1993         Sep    Monday
543718  1997-04-20   20      4  1997         Apr    Sunday

[13656 rows x 6 columns]

In [36]:
f = open("dates.sql", "a",encoding='utf-8')
for index,row in date.iterrows(): 
    f.write("INSERT INTO music_schema.date (" +"date_id"+","+"day_number"+","+"month_number"+","+"year_number"+","+"month_label"+","+"week_day"+")")
    f.write('\n')
    f.write("VALUES(" + "'"+str(row["Release"])+"'"+","+str(row["day"])+","+str(row["month"])+","+str(row["year"])+","+"'"+str(row["month_label"])+"'"+","+"'"+str(row["week_day"])+"');")
    f.write('\n')
    f.write('\n')
f.close()

## Creating the track table

In [37]:
everyNoise = pd.read_csv("CSVs/every-noise-at-once.csv")
everyNoise = everyNoise.drop(columns=["Instrumentalness","Artists","Artists_Id","Key"])
everyNoise = everyNoise.dropna(subset=["Name","Id"])
everyNoise = everyNoise.drop_duplicates(subset=["Id"])
everyNoise = everyNoise.dropna(subset=["Release"])

In [38]:
everyNoise

,Name,Id,Release,Duration,Genre,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Valeance,Tempo
0,Don't Go Yet,1058fW9H3fZA6QjYCdOBad,2021-07-23,164842,pop,0.666,0.7960,-6.967,0.1030,0.0492,0.0442,0.6100,110.108
1,What A Time (feat. Niall Horan),5WtfUKzXircvW8l5aaVZWT,2019-01-24,173307,pop,0.516,0.4670,-6.184,0.0302,0.6620,0.0853,0.3860,132.861
2,Scars To Your Beautiful,42ydLwx4i5V49RXHOozJZq,2016-03-11,230227,pop,0.319,0.7390,-5.740,0.2720,0.0285,0.1110,0.4490,194.169
3,Reckless,5ajjAnNRh8bxFvaVHzpPjh,2021-06-04,203385,pop,0.386,0.4260,-6.642,0.0363,0.8070,0.1400,0.2610,180.104
4,Dusk Till Dawn (feat. Sia) - Radio Edit,3e7sxremeOE3wTySiOhGiP,2018-12-14,239000,pop,0.259,0.4370,-6.589,0.0386,0.1020,0.1060,0.0951,180.042
...,...,...,...,...,...,...,...,...,...,...,...,...,...
544396,"String Trio in C Minor, Op. 9, No. 3: IV. Fina...",3LKmf7uAN2xhK87elaGvKN,2011-06-07,368571,ugandan traditional,0.464,0.0671,-20.093,0.0424,0.8170,0.1190,0.4090,105.152
544397,"Divertimento in E-Flat Major, K. 563 ('Di sei ...",5Vqmp5wdAiQMn1DaQK161R,2020-08-07,548000,ugandan traditional,0.365,0.1250,-16.972,0.0402,0.9470,0.1130,0.3490,118.562
544398,"Baryton Trio No. 109 in C Major, Hob.XI:109: I...",4FcVIxHUKVY9UQ4B7ZDJll,2014-07-15,234707,ugandan traditional,0.371,0.0200,-20.062,0.0479,0.9830,0.0904,0.1200,74.202
544399,"Concert Trio No. 1 in B-Flat Major, Op. 1, No....",7kCpFbgNcm8oyvTBfVTm8B,2014-07-15,231360,ugandan traditional,0.256,0.0740,-21.666,0.0502,0.9650,0.1030,0.1210,103.362
544400,"String Trio No. 1, Op. 34: I. Toccata",6RvJctszO0WQN1DmvWhfWK,2000-10-01,326573,ugandan traditional,0.356,0.1870,-19.465,0.0421,0.9440,0.2860,0.3880,141.980

#### les donneÃ©s sont vÃ©rifiÃ©s qu'ils sont bien homogÃ¨nes

In [39]:

f = open("songs2.sql", "a",encoding='utf-8')
for index,row in everyNoise.iterrows(): 
    f.write("INSERT INTO music_schema.track (" +"track_id"+","+"track_name"+","+"release_date"+","+"genre"+","+"duration"+","+"danceability"+","+"speechiness"+","+"energy"+","+"loudness"+","+"acousticness"+","+"liveness"+","+"valence"+","+"tempo"+")")
    f.write('\n')
    f.write("VALUES(" + "'"+str(row["Id"])+"'"+","+"'"+str(row["Name"]).replace("'","")+"'"+","+"'"+str(row["Release"])+"'"+","+"'"+str(row["Genre"]).replace("'","")+"'"+","+str(row["Duration"])+","+str(row["Danceability"])+","+str(row["Speechiness"])+","+str(row["Energy"])+","+str(row["Loudness"])+","+str(row["Acousticness"])+","+str(row["Liveness"])+","+str(row["Valeance"])+","+str(row["Tempo"])+");")
    f.write('\n')
    f.write('\n')
f.close()

### Separating miltivalued attribute into  a new table

In [40]:
temp= pd.read_csv("CSVs/every-noise-at-once.csv")
f = open("test.csv", "a",encoding='utf-8')
for index,row in temp.iterrows():
    for artist in (row["Artists_Id"].split(",")):  
        f.write(row["Id"]+","+artist)
        f.write('\n')
f.close()
#le reste de netoyage est fait Ã  la main avec vscode

In [41]:
everyNoise =  pd.read_csv("CSVs/every-noise-at-once.csv")
songs = everyNoise.drop(columns=["Artists","Artists_Id"])
songs

,Name,Id,Release,Duration,Genre,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valeance,Tempo
0,Don't Go Yet,1058fW9H3fZA6QjYCdOBad,2021-07-23,164842,pop,0.666,0.7960,10,-6.967,0.1030,0.0492,0.000000,0.0442,0.6100,110.108
1,What A Time (feat. Niall Horan),5WtfUKzXircvW8l5aaVZWT,2019-01-24,173307,pop,0.516,0.4670,0,-6.184,0.0302,0.6620,0.000000,0.0853,0.3860,132.861
2,Scars To Your Beautiful,42ydLwx4i5V49RXHOozJZq,2016-03-11,230227,pop,0.319,0.7390,0,-5.740,0.2720,0.0285,0.000000,0.1110,0.4490,194.169
3,Reckless,5ajjAnNRh8bxFvaVHzpPjh,2021-06-04,203385,pop,0.386,0.4260,3,-6.642,0.0363,0.8070,0.000000,0.1400,0.2610,180.104
4,Dusk Till Dawn (feat. Sia) - Radio Edit,3e7sxremeOE3wTySiOhGiP,2018-12-14,239000,pop,0.259,0.4370,11,-6.589,0.0386,0.1020,0.000001,0.1060,0.0951,180.042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544396,"String Trio in C Minor, Op. 9, No. 3: IV. Fina...",3LKmf7uAN2xhK87elaGvKN,2011-06-07,368571,ugandan traditional,0.464,0.0671,5,-20.093,0.0424,0.8170,0.460000,0.1190,0.4090,105.152
544397,"Divertimento in E-Flat Major, K. 563 ('Di sei ...",5Vqmp5wdAiQMn1DaQK161R,2020-08-07,548000,ugandan traditional,0.365,0.1250,10,-16.972,0.0402,0.9470,0.637000,0.1130,0.3490,118.562
544398,"Baryton Trio No. 109 in C Major, Hob.XI:109: I...",4FcVIxHUKVY9UQ4B7ZDJll,2014-07-15,234707,ugandan traditional,0.371,0.0200,0,-20.062,0.0479,0.9830,0.026400,0.0904,0.1200,74.202
544399,"Concert Trio No. 1 in B-Flat Major, Op. 1, No....",7kCpFbgNcm8oyvTBfVTm8B,2014-07-15,231360,ugandan traditional,0.256,0.0740,3,-21.666,0.0502,0.9650,0.397000,0.1030,0.1210,103.362
544400,"String Trio No. 1, Op. 34: I. Toccata",6RvJctszO0WQN1DmvWhfWK,2000-10-01,326573,ugandan traditional,0.356,0.1870,9,-19.465,0.0421,0.9440,0.782000,0.2860,0.3880,141.980

### Creating track_artist table

In [42]:
songArtist = pd.read_csv("CSVs/songArtist.csv")
songArtist = songArtist.drop_duplicates(subset=["Artist_ID"])
songArtist = songArtist.drop_duplicates(subset=["Song_ID"])

songArtist

                       Song_ID               Artist_ID
0       1058fW9H3fZA6QjYCdOBad  4nDoRrQiYLoBzwC5BhVJzF
1       5WtfUKzXircvW8l5aaVZWT  0ZED1XzwlLHW4ZaG4lOT6m
3       42ydLwx4i5V49RXHOozJZq  2wUjUUtkb5lvLKcGKsKqsR
4       5ajjAnNRh8bxFvaVHzpPjh  2kRfqPViCqYdSGhYSM9R0Q
5       3e7sxremeOE3wTySiOhGiP  5ZsFI1h6hIdQRw2ti0hz81
...                        ...                     ...
607079  6F4qWBulpQ8mCxKShRFVUs  4gPWEjFEfpLixsjC3kxWUI
607083  614tL9vY6Y01VC4i2xBU8J  6s2e70QqXiE8OSKD4Tju8F
607085  7KOHV55n2T03l4Kn16TgK1  7Dy8omz0NLSb5214ldC8Cl
607103  7qugDuzbfDdHDEhy8YXnEd  5Bzn7cX511DWq55P9e0q8c
607136  3jpXaJX3INxkyU1n5eXELG  7eq9PKQ2xIQOufympUHqIP

[332872 rows x 2 columns]

In [43]:

songArtist = pd.read_csv("CSVs/SongArtist.csv")
f = open("songArtist.sql", "a",encoding='utf-8')
for index,row in songArtist.iterrows(): 
    f.write("INSERT INTO music_schema.track_artist (" +"Song_ID"+","+"Artist_ID"+")")
    f.write('\n')
    f.write("VALUES(" + "'"+row["Song_ID"]+"'"+","+"'"+row["Artist_ID"]+"');")
    f.write('\n')
    f.write('\n')
f.close()

### Creating artist table

In [44]:
artists = pd.read_csv("CSVs/artists.csv")
artists

                    artist_id            artist_name  followers
0      4mGnpjhqgx4RUdsIJiURdo          Juliano Cezar      23230
1      1dLnVku4VQUOLswwDFvRc9         The Grenadines        313
2      6YVY310fjfUzKi8hiqR7iK                Gangway       1596
3      2VElyouiCfoYPDJluzwJwK                  FADES        149
4      4agVy03qW8juSysCTUOuDI    Jean-Pierre Guignon         11
...                       ...                    ...        ...
48711  48YkQQTWzmT248VY8DF7Fv  Profetas y Freneticos       1212
48712  1OgaghfYd1qr8DFoNrfDNk               Sinergia      57973
48713  7o9kdTx6RmO12iAVVsNehd         The Superjesus      20870
48714  6n3YUZcayLRuAunJUUelvz           Regurgitator      33923
48715  47yawJswuSfSvizYhItoOP     Something For Kate      42026

[48716 rows x 3 columns]

In [45]:

f = open("artist.sql", "a",encoding='utf-8')
for index,row in artists.iterrows(): 
    f.write("INSERT INTO artist (" +"artist_id"+","+"artist_name"+","+"followers"+")")
    f.write('\n')
    f.write("VALUES(" + "'"+str(row["artist_id"])+"'"+","+"'"+str(row["artist_name"]).replace("'","")+"'"+","+str(row["followers"])+");")
    f.write('\n')
    f.write('\n')
f.close()

### Creating artist csv

In [46]:
artistsFile = pd.read_csv("CSVs/artists.csv")
for index,row in artistsFile.iterrows(): 
    if not(str(row["artist_id"])) : 
        artistsFile.drop(index,inplace=True)
for index,row in artistsFile.iterrows(): 

    if (str(row["artist_name"])).isnumeric() : 
        artistsFile.drop(index,inplace=True)
for index,row in artistsFile.iterrows(): 

    if ((str(row["followers"]).isnumeric())) == False :
        artistsFile.drop(index,inplace=True)    
artistsFile.to_csv("artists.csv")